from .ast.expression import ASTExpression
from .distribution import Distribution
from .enums import *
from .errors import *
from .roll import RollResult
from .stringifier import Stringifier

def parse(expr: str | ASTExpression) -> ASTExpression: ...
def roll(
    expr: str | ASTExpression, stringifier: Stringifier | None = None, advantage: Advantage = ...
) -> RollResult: ...
def seed(s: int | float | str | bytes | bytearray | None = None) -> None: ...
def distribution(expr: str | ASTExpression) -> Distribution: ...
