from typing import Any

from lark import Token as Token, Transformer

from .ast.binop import ASTBinOp as ASTBinOp
from .ast.dice import ASTDice as ASTDice
from .ast.expression import ASTExpression as ASTExpression
from .ast.literal import ASTLiteral as ASTLiteral
from .ast.node import ASTNode as ASTNode
from .ast.operators import (
    AdvantageCategory as AdvantageCategory,
    BinaryOperator as BinaryOperator,
    DiceCategory as DiceCategory,
    ExpressionCategory as ExpressionCategory,
    Operator as Operator,
    Selector as Selector,
    SetCategory as SetCategory,
    UnaryOperator as UnaryOperator,
)
from .ast.parenthetical import ASTParenthetical as ASTParenthetical
from .ast.unop import ASTUnOp as ASTUnOp
from .errors import RollError as RollError, RollSyntaxError as RollSyntaxError

class RollTransformer(Transformer[Any, Any]):
    def expr(self, expr: tuple[ASTNode]) -> ASTExpression: ...
    def comparison(self, binop: tuple[ASTNode, Token, ASTNode]) -> ASTBinOp: ...
    def a_num(self, binop: tuple[ASTNode, Token, ASTNode]) -> ASTBinOp: ...
    def m_num(self, binop: tuple[ASTNode, Token, ASTNode]) -> ASTBinOp: ...
    def u_num(self, unop: tuple[Token, ASTNode]) -> ASTUnOp: ...
    def literal(self, literal: tuple[Token]) -> ASTLiteral: ...
    def parenthetical(self, num: tuple[ASTNode] | tuple[ASTNode, Operator]) -> ASTParenthetical: ...
    def dice(self, opdice: Any) -> ASTDice: ...
    def dice_op(self, opsel: tuple[Operator]) -> Operator: ...
    def dice_expr(self, dice: Any) -> ASTDice: ...
    def selector(self, sel: Any) -> Selector: ...
    def num_selector(self, sel: Any) -> Selector: ...
    def dice_operator(self, opsel: tuple[DiceCategory, Selector]) -> Operator: ...
    def set_operator(self, opsel: tuple[SetCategory, Selector]) -> Operator: ...
    def advantage_operator(self, opsel: tuple[AdvantageCategory] | tuple[AdvantageCategory, int]) -> Operator: ...
    def expression_operator(self, opsel: tuple[ExpressionCategory]) -> Operator: ...

class Parser:
    def __init__(self, grammar_path: str) -> None: ...
    def parse(self, expr: str | bytes, start: str | None = None) -> ASTExpression:
        """Parse an expression string to an expression AST tree."""
