from typing import Any

from lark import Lark, Token as Token, Transformer

from .ast.binop import ASTBinOp as ASTBinOp
from .ast.dice import ASTDice as ASTDice
from .ast.expression import ASTExpression as ASTExpression
from .ast.literal import ASTLiteral as ASTLiteral
from .ast.node import ASTNode as ASTNode
from .ast.operators import (
    BinaryOperator as BinaryOperator,
    Operator as Operator,
    OperatorCategory as OperatorCategory,
    Selector as Selector,
    UnaryOperator as UnaryOperator,
)
from .ast.parenthetical import ASTParenthetical as ASTParenthetical
from .ast.unevaluated import ASTUnevaluated as ASTUnevaluated
from .ast.unop import ASTUnOp as ASTUnOp
from .errors import RollError as RollError, RollSyntaxError as RollSyntaxError

class DiceTransformer(Transformer[Any, Any]):
    def expr(self, expr: tuple[Any, ...]) -> ASTLiteral | ASTDice: ...
    def dice(self, opdice: Any) -> ASTDice: ...
    def dice_operator(self, opsel: tuple[OperatorCategory, Selector | None]) -> Operator: ...
    def dice_expr(self, dice: Any) -> ASTDice: ...
    def selector(self, sel: Any) -> Selector: ...
    def num_selector(self, sel: Any) -> Selector: ...

class ExpressionTransformer(Transformer[Any, Any]):
    def __init__(self, dice_grammar: Lark) -> None: ...
    def expr(self, expr: tuple[ASTNode]) -> ASTExpression: ...
    def comparison(self, binop: tuple[ASTNode, Token, ASTNode]) -> ASTBinOp: ...
    def a_num(self, binop: tuple[ASTNode, Token, ASTNode]) -> ASTBinOp: ...
    def m_num(self, binop: tuple[ASTNode, Token, ASTNode]) -> ASTBinOp: ...
    def u_num(self, unop: tuple[Token, ASTNode]) -> ASTUnOp: ...
    def parenthetical(self, num: Any) -> ASTParenthetical: ...
    def value(self, token: tuple[Token]) -> ASTLiteral | ASTDice | ASTUnevaluated: ...
    def unevaluated(self, unevaluated: str) -> ASTUnevaluated: ...

class Parser:
    def __init__(self, dice_grammar_path: str, expression_grammar_path: str) -> None: ...
    def parse(self, expr: str | bytes, start: str | None = None) -> ASTExpression:
        """Parse an expression string to an expression AST tree."""
