from collections.abc import Sequence

from .dice import ASTDice as ASTDice
from .die import DiceSize as DiceSize, Die as Die
from .node import ASTNode as ASTNode, Number as Number
from ..context import RollContext as RollContext
from ..distribution import Distribution as Distribution

LiteralValue = int | float

class Literal(Number):
    """Literals are literal numeric values."""

    value: int
    def __init__(self, value: int, ast: ASTNode) -> None: ...
    @property
    def total(self) -> int: ...
    @property
    def children(self) -> Sequence[Number]: ...
    def copy(self) -> Literal: ...
    def extract_dice(self) -> Sequence[Die]: ...

class ASTLiteral(ASTNode):
    """Literals are literal numeric values."""

    value: int | float
    def __init__(self, value: int | float) -> None: ...
    @property
    def children(self) -> Sequence[ASTNode]: ...
    def copy(self) -> ASTLiteral: ...
    def roll(self, context: RollContext) -> tuple[Literal, Sequence[Literal]]: ...
    def distribution(self) -> Distribution: ...
    @property
    def is_comparison(self) -> bool: ...
    def find_dice(self, count: int, size: DiceSize) -> ASTDice | None: ...
