from collections.abc import Sequence

from .dice import ASTDice as ASTDice, find_from_advantage as find_from_advantage
from .die import DiceSize as DiceSize, Die as Die
from .node import ASTNode as ASTNode, Number as Number
from .operators import AdvantageCategory as AdvantageCategory, Operator as Operator
from ..context import RollContext as RollContext
from ..distribution import Distribution as Distribution
from ..errors import RollError as RollError
from ..utils import apply_advantage_to_distribution as apply_advantage_to_distribution

class Parenthetical(Number):
    """Parentheticals contain values between parentheses."""

    value: Number
    def __init__(self, value: Number, ast: ASTNode) -> None: ...
    @property
    def total(self) -> int: ...
    @property
    def children(self) -> Sequence[Number]: ...
    def copy(self) -> Number: ...
    def extract_dice(self) -> Sequence[Die]: ...

class ASTParenthetical(ASTNode):
    """Expressions are usually the root of all ASTs."""

    value: ASTNode
    operator: Operator | None
    def __init__(self, value: ASTNode, operator: Operator | None) -> None: ...
    def copy(self) -> ASTParenthetical: ...
    @property
    def children(self) -> Sequence[ASTNode]: ...
    def roll(self, context: RollContext) -> tuple[Parenthetical, Sequence[Parenthetical]]: ...
    def distribution(self) -> Distribution: ...
    @property
    def is_comparison(self) -> bool: ...
    def find_dice(self, count: int, size: DiceSize) -> ASTDice | None: ...
