from collections.abc import Sequence
from typing import Literal

from .dice import ASTDice as ASTDice
from .node import ASTNode as ASTNode, Number as Number
from ..context import RollContext as RollContext
from ..distribution import Distribution as Distribution
from ..errors import RollSyntaxError as RollSyntaxError

class ASTUnevaluated(ASTNode):
    value: str
    def __init__(self, value: str) -> None: ...
    def copy(self) -> ASTUnevaluated: ...
    @property
    def children(self) -> Sequence[ASTNode]: ...
    def roll(self, context: RollContext) -> tuple[Number, Sequence[Number]]: ...
    def distribution(self) -> Distribution: ...
    @property
    def is_comparison(self) -> bool: ...
    def find_dice(self, count: int, size: int | Literal["%"]) -> ASTDice | None: ...
