from collections.abc import Sequence

from .dice import ASTDice as ASTDice
from .die import DiceSize as DiceSize, Die as Die
from .node import ASTNode as ASTNode, Number as Number
from .operators import UnaryOperator as UnaryOperator
from ..context import RollContext as RollContext
from ..distribution import Distribution as Distribution

class UnOp(Number):
    """UnOps are numbers modified by a unary operator."""

    op: UnaryOperator
    value: Number
    def __init__(self, op: UnaryOperator, value: Number, ast: ASTNode) -> None: ...
    @property
    def total(self) -> int: ...
    @property
    def children(self) -> Sequence[Number]: ...
    def copy(self) -> Number: ...
    def extract_dice(self) -> Sequence[Die]: ...

class ASTUnOp(ASTNode):
    """UnOps are nodes modified by a unary operator."""

    op: UnaryOperator
    value: ASTNode
    def __init__(self, op: UnaryOperator, value: ASTNode) -> None: ...
    @property
    def children(self) -> Sequence[ASTNode]: ...
    def copy(self) -> ASTUnOp: ...
    def roll(self, context: RollContext) -> tuple[UnOp, Sequence[UnOp]]: ...
    def distribution(self) -> Distribution: ...
    @property
    def is_comparison(self) -> bool: ...
    def find_dice(self, count: int, size: DiceSize) -> ASTDice | None: ...
