// Dice rolling grammar - Avrae spec

expr: num

// math and operators, PMDAS
?num: comparison

?comparison: (comparison COMP_OPERATOR _WS?)? a_num _WS?
COMP_OPERATOR: "==" | ">=" | "<=" | "!=" | "<" | ">"

?a_num: (a_num A_OP _WS?)? m_num _WS?
A_OP: "+" | "-"

?m_num: (m_num M_OP _WS?)? u_num _WS?
M_OP: "*" | "//" | "/" | "%"

?u_num: num_expr | U_OP _WS? u_num
U_OP: "+" | "-"

// numbers
?num_expr: (parenthetical | dice | literal)

literal: INTEGER | DECIMAL

parenthetical: "(" _WS? num _WS? ")" advantage_operator?

// dice
?dice: dice_expr dice_op*

dice_op: dice_operator | set_operator | advantage_operator | expression_operator

SET_OPERATOR: "k" | "p"
DICE_OPERATOR: "rr" | "ro" | "ra" | "e" | "mi" | "ma" | "rs"
ADVANTAGE_OPERATOR: "adv" | "dis"
EXPRESSION_OPERATOR: "red"

set_operator: SET_OPERATOR selector
dice_operator: DICE_OPERATOR selector
advantage_operator: ADVANTAGE_OPERATOR num_selector?
expression_operator: EXPRESSION_OPERATOR

dice_expr: INTEGER? "d" DICE_VALUE

?selector: [SELTYPE] INTEGER
?num_selector: INTEGER

DICE_VALUE: INTEGER | "%"
SELTYPE: "l" | "h" | COMP_OPERATOR

// whitespace
_WS: /[ \t\f\r\n]/+

// useful constants
%import common.INT -> INTEGER
%import common.DECIMAL